import './global.css';

export const metadata = {
  title: 'My Shop',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {/* Simple Navbar */}
        <nav className="bg-white shadow p-4 mb-4 flex gap-4 justify-center">
          <a href="/" className="text-blue-600 font-bold hover:underline">Login</a>
          <span className="text-gray-300">|</span>
          <a href="/product" className="text-blue-600 font-bold hover:underline">Shop</a>
        </nav>
        
        {children}
      </body>
    </html>
  );
}